# Funding transparency per RSR requirements
# These are funding links for the Gitvisor project

github: hyperpolymath
# ko_fi: # Add if applicable
# open_collective: # Add if applicable
# liberapay: # Add if applicable
custom: []
